export {default as Seo} from "./seo"
export {default as AppProvider} from "./appProvider"
export {default as Home} from "./home"
export {default as About} from "./about"
export {default as Projects} from "./projects"
export {default as Skills} from "./skills"
export {default as Footer} from "./footer"
export {default as Scripts} from "./scripts"